//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v44.factura.compra;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodigoType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CodigoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Tipo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Codigo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="20"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodigoType", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronicaCompra", propOrder = {
    "tipo",
    "codigo"
})
public class CodigoType {

    /**
     * Será obligatorio para las líneas de detalle que utilicen uno de
     * los códigos de producto/servicio de "surtidos" que estén
     * habilitados en el CAByS.
     * En el caso de la inclusión de paquetes, surtidos o combos,
     * entendidos como la combinación de más de dos productos
     * con diferentes códigos de producto/servicio, se debe
     * seleccionar el código 03 "Código del producto asignado por la
     * industria" de la nota 12 e incluir en el campo "código" el
     * respectivo código "SKU", GTIN o equivalentes, con el que el
     * paquete este identificado en la industria. Estos códigos deben
     * ser verificables en los catálogos disponibles en la industria.
     * 
     */
    @XmlElement(name = "Tipo", required = true)
    protected String tipo;
    /**
     * Será obligatorio para las líneas de detalle que utilicen uno de
     * los códigos de producto/servicio de "surtidos" que estén
     * habilitados en el CAByS.
     * 
     */
    @XmlElement(name = "Codigo", required = true)
    protected String codigo;

    /**
     * Será obligatorio para las líneas de detalle que utilicen uno de
     * los códigos de producto/servicio de "surtidos" que estén
     * habilitados en el CAByS.
     * En el caso de la inclusión de paquetes, surtidos o combos,
     * entendidos como la combinación de más de dos productos
     * con diferentes códigos de producto/servicio, se debe
     * seleccionar el código 03 "Código del producto asignado por la
     * industria" de la nota 12 e incluir en el campo "código" el
     * respectivo código "SKU", GTIN o equivalentes, con el que el
     * paquete este identificado en la industria. Estos códigos deben
     * ser verificables en los catálogos disponibles en la industria.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipo()
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Será obligatorio para las líneas de detalle que utilicen uno de
     * los códigos de producto/servicio de "surtidos" que estén
     * habilitados en el CAByS.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigo()
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

}
