//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v43.factura.compra;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Clave" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}ClaveType"/>
 *         <element name="CodigoActividad">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="6"/>
 *               <minLength value="6"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroConsecutivo" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}NumeroConsecutivoType"/>
 *         <element name="FechaEmision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="Emisor" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}EmisorType"/>
 *         <element name="Receptor" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}ReceptorType"/>
 *         <element name="CondicionVenta">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="06"/>
 *               <enumeration value="07"/>
 *               <enumeration value="08"/>
 *               <enumeration value="09"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PlazoCredito" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="10"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MedioPago" maxOccurs="4">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DetalleServicio">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="LineaDetalle" maxOccurs="1000">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="NumeroLinea" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             <element name="Codigo" minOccurs="0">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   <maxLength value="13"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="CodigoComercial" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}CodigoType" maxOccurs="5" minOccurs="0"/>
 *                             <element name="Cantidad">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   <totalDigits value="16"/>
 *                                   <fractionDigits value="3"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="UnidadMedida" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}UnidadMedidaType"/>
 *                             <element name="UnidadMedidaComercial" minOccurs="0">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   <maxLength value="20"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="Detalle">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   <maxLength value="200"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="PrecioUnitario" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                             <element name="MontoTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                             <element name="Descuento" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DescuentoType" maxOccurs="5" minOccurs="0"/>
 *                             <element name="SubTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                             <element name="BaseImponible" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                             <element name="Impuesto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}ImpuestoType" maxOccurs="unbounded" minOccurs="0"/>
 *                             <element name="ImpuestoNeto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                             <element name="MontoTotalLinea" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="OtrosCargos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}OtrosCargosType" maxOccurs="15" minOccurs="0"/>
 *         <element name="ResumenFactura">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="CodigoTipoMoneda" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}CodigoMonedaType" minOccurs="0"/>
 *                   <element name="TotalServGravados" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalServExentos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalServExonerado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalMercanciasGravadas" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalMercanciasExentas" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalMercExonerada" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalGravado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalExento" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalExonerado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalVenta" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                   <element name="TotalDescuentos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalVentaNeta" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                   <element name="TotalImpuesto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalOtrosCargos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
 *                   <element name="TotalComprobante" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="InformacionReferencia" maxOccurs="10" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="TipoDoc">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <enumeration value="01"/>
 *                         <enumeration value="02"/>
 *                         <enumeration value="03"/>
 *                         <enumeration value="04"/>
 *                         <enumeration value="05"/>
 *                         <enumeration value="06"/>
 *                         <enumeration value="07"/>
 *                         <enumeration value="08"/>
 *                         <enumeration value="09"/>
 *                         <enumeration value="10"/>
 *                         <enumeration value="11"/>
 *                         <enumeration value="12"/>
 *                         <enumeration value="13"/>
 *                         <enumeration value="14"/>
 *                         <enumeration value="15"/>
 *                         <enumeration value="99"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="Numero" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="50"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="FechaEmision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   <element name="Codigo" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <enumeration value="01"/>
 *                         <enumeration value="02"/>
 *                         <enumeration value="03"/>
 *                         <enumeration value="04"/>
 *                         <enumeration value="05"/>
 *                         <enumeration value="99"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="Razon" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="180"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Otros" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="OtroTexto" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <simpleContent>
 *                         <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                           <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         </extension>
 *                       </simpleContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="OtroContenido" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <any processContents='lax' namespace='##other'/>
 *                           </sequence>
 *                           <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clave",
    "codigoActividad",
    "numeroConsecutivo",
    "fechaEmision",
    "emisor",
    "receptor",
    "condicionVenta",
    "plazoCredito",
    "medioPago",
    "detalleServicio",
    "otrosCargos",
    "resumenFactura",
    "informacionReferencia",
    "otros",
    "signature"
})
@XmlRootElement(name = "FacturaElectronicaCompra", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
public class FacturaElectronicaCompra {

    /**
     * Corresponde a la clave del comprobante. Es un campo de 50 posiciones y se
     *                             tiene que utilizar para la consulta del código QR. Ver nota 1 y 4.1
     * 
     */
    @XmlElement(name = "Clave", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected String clave;
    /**
     * Se debe indicar el código de la actividad económica a la cual corresponde el
     *                             comprobante electrónico
     * 
     */
    @XmlElement(name = "CodigoActividad", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected String codigoActividad;
    /**
     * Numeración consecutiva del comprobante
     * 
     */
    @XmlElement(name = "NumeroConsecutivo", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected String numeroConsecutivo;
    @XmlElement(name = "FechaEmision", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEmision;
    /**
     * Emisor del documento
     * 
     */
    @XmlElement(name = "Emisor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected EmisorType emisor;
    /**
     * Receptor del documento
     * 
     */
    @XmlElement(name = "Receptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected ReceptorType receptor;
    /**
     * Condiciones de la venta: 01 Contado, 02 Crédito, 03 Consignación, 04 Apartado,
     *                             05 Arrendamiento con opción de compra, 06 Arrendamiento en función financiera, 07 Cobro a
     *                             favor de un tercero, 08 servicxios prestados al estado a credito, 09 pago del servicio
     *                             prestado al estado, 99 Otros
     * 
     */
    @XmlElement(name = "CondicionVenta", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected String condicionVenta;
    /**
     * Plazo del crédito, es obligatorio cuando la venta del producto o prestación
     *                             del servicio sea a crédito
     * 
     */
    @XmlElement(name = "PlazoCredito", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
    protected String plazoCredito;
    /**
     * Corresponde al medio de pago empleado: 01 Efectivo, 02 Tarjeta, 03 Cheque, 04
     *                             Transferencia - depósito bancario, 05 - Recaudado por terceros, 99 Otros
     * 
     */
    @XmlElement(name = "MedioPago", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected List<String> medioPago;
    /**
     * Detalle de la mercancia o servicio prestado.
     * 
     */
    @XmlElement(name = "DetalleServicio", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected FacturaElectronicaCompra.DetalleServicio detalleServicio;
    /**
     * Información sobre otros cargos
     * 
     */
    @XmlElement(name = "OtrosCargos", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
    protected List<OtrosCargosType> otrosCargos;
    @XmlElement(name = "ResumenFactura", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
    protected FacturaElectronicaCompra.ResumenFactura resumenFactura;
    @XmlElement(name = "InformacionReferencia", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
    protected List<FacturaElectronicaCompra.InformacionReferencia> informacionReferencia;
    @XmlElement(name = "Otros", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
    protected FacturaElectronicaCompra.Otros otros;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;

    /**
     * Corresponde a la clave del comprobante. Es un campo de 50 posiciones y se
     *                             tiene que utilizar para la consulta del código QR. Ver nota 1 y 4.1
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClave() {
        return clave;
    }

    /**
     * Sets the value of the clave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getClave()
     */
    public void setClave(String value) {
        this.clave = value;
    }

    /**
     * Se debe indicar el código de la actividad económica a la cual corresponde el
     *                             comprobante electrónico
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoActividad() {
        return codigoActividad;
    }

    /**
     * Sets the value of the codigoActividad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigoActividad()
     */
    public void setCodigoActividad(String value) {
        this.codigoActividad = value;
    }

    /**
     * Numeración consecutiva del comprobante
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroConsecutivo() {
        return numeroConsecutivo;
    }

    /**
     * Sets the value of the numeroConsecutivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroConsecutivo()
     */
    public void setNumeroConsecutivo(String value) {
        this.numeroConsecutivo = value;
    }

    /**
     * Gets the value of the fechaEmision property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmision() {
        return fechaEmision;
    }

    /**
     * Sets the value of the fechaEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEmision(XMLGregorianCalendar value) {
        this.fechaEmision = value;
    }

    /**
     * Emisor del documento
     * 
     * @return
     *     possible object is
     *     {@link EmisorType }
     *     
     */
    public EmisorType getEmisor() {
        return emisor;
    }

    /**
     * Sets the value of the emisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmisorType }
     *     
     * @see #getEmisor()
     */
    public void setEmisor(EmisorType value) {
        this.emisor = value;
    }

    /**
     * Receptor del documento
     * 
     * @return
     *     possible object is
     *     {@link ReceptorType }
     *     
     */
    public ReceptorType getReceptor() {
        return receptor;
    }

    /**
     * Sets the value of the receptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceptorType }
     *     
     * @see #getReceptor()
     */
    public void setReceptor(ReceptorType value) {
        this.receptor = value;
    }

    /**
     * Condiciones de la venta: 01 Contado, 02 Crédito, 03 Consignación, 04 Apartado,
     *                             05 Arrendamiento con opción de compra, 06 Arrendamiento en función financiera, 07 Cobro a
     *                             favor de un tercero, 08 servicxios prestados al estado a credito, 09 pago del servicio
     *                             prestado al estado, 99 Otros
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondicionVenta() {
        return condicionVenta;
    }

    /**
     * Sets the value of the condicionVenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCondicionVenta()
     */
    public void setCondicionVenta(String value) {
        this.condicionVenta = value;
    }

    /**
     * Plazo del crédito, es obligatorio cuando la venta del producto o prestación
     *                             del servicio sea a crédito
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlazoCredito() {
        return plazoCredito;
    }

    /**
     * Sets the value of the plazoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPlazoCredito()
     */
    public void setPlazoCredito(String value) {
        this.plazoCredito = value;
    }

    /**
     * Corresponde al medio de pago empleado: 01 Efectivo, 02 Tarjeta, 03 Cheque, 04
     *                             Transferencia - depósito bancario, 05 - Recaudado por terceros, 99 Otros
     * 
     * Gets the value of the medioPago property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medioPago property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMedioPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the medioPago property.
     */
    public List<String> getMedioPago() {
        if (medioPago == null) {
            medioPago = new ArrayList<>();
        }
        return this.medioPago;
    }

    /**
     * Detalle de la mercancia o servicio prestado.
     * 
     * @return
     *     possible object is
     *     {@link FacturaElectronicaCompra.DetalleServicio }
     *     
     */
    public FacturaElectronicaCompra.DetalleServicio getDetalleServicio() {
        return detalleServicio;
    }

    /**
     * Sets the value of the detalleServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacturaElectronicaCompra.DetalleServicio }
     *     
     * @see #getDetalleServicio()
     */
    public void setDetalleServicio(FacturaElectronicaCompra.DetalleServicio value) {
        this.detalleServicio = value;
    }

    /**
     * Información sobre otros cargos
     * 
     * Gets the value of the otrosCargos property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otrosCargos property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getOtrosCargos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtrosCargosType }
     * </p>
     * 
     * 
     * @return
     *     The value of the otrosCargos property.
     */
    public List<OtrosCargosType> getOtrosCargos() {
        if (otrosCargos == null) {
            otrosCargos = new ArrayList<>();
        }
        return this.otrosCargos;
    }

    /**
     * Gets the value of the resumenFactura property.
     * 
     * @return
     *     possible object is
     *     {@link FacturaElectronicaCompra.ResumenFactura }
     *     
     */
    public FacturaElectronicaCompra.ResumenFactura getResumenFactura() {
        return resumenFactura;
    }

    /**
     * Sets the value of the resumenFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacturaElectronicaCompra.ResumenFactura }
     *     
     */
    public void setResumenFactura(FacturaElectronicaCompra.ResumenFactura value) {
        this.resumenFactura = value;
    }

    /**
     * Gets the value of the informacionReferencia property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informacionReferencia property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInformacionReferencia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacturaElectronicaCompra.InformacionReferencia }
     * </p>
     * 
     * 
     * @return
     *     The value of the informacionReferencia property.
     */
    public List<FacturaElectronicaCompra.InformacionReferencia> getInformacionReferencia() {
        if (informacionReferencia == null) {
            informacionReferencia = new ArrayList<>();
        }
        return this.informacionReferencia;
    }

    /**
     * Gets the value of the otros property.
     * 
     * @return
     *     possible object is
     *     {@link FacturaElectronicaCompra.Otros }
     *     
     */
    public FacturaElectronicaCompra.Otros getOtros() {
        return otros;
    }

    /**
     * Sets the value of the otros property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacturaElectronicaCompra.Otros }
     *     
     */
    public void setOtros(FacturaElectronicaCompra.Otros value) {
        this.otros = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="LineaDetalle" maxOccurs="1000">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="NumeroLinea" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   <element name="Codigo" minOccurs="0">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         <maxLength value="13"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="CodigoComercial" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}CodigoType" maxOccurs="5" minOccurs="0"/>
     *                   <element name="Cantidad">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         <totalDigits value="16"/>
     *                         <fractionDigits value="3"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="UnidadMedida" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}UnidadMedidaType"/>
     *                   <element name="UnidadMedidaComercial" minOccurs="0">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         <maxLength value="20"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="Detalle">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         <maxLength value="200"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="PrecioUnitario" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *                   <element name="MontoTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *                   <element name="Descuento" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DescuentoType" maxOccurs="5" minOccurs="0"/>
     *                   <element name="SubTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *                   <element name="BaseImponible" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *                   <element name="Impuesto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}ImpuestoType" maxOccurs="unbounded" minOccurs="0"/>
     *                   <element name="ImpuestoNeto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *                   <element name="MontoTotalLinea" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineaDetalle"
    })
    public static class DetalleServicio {

        /**
         * Cada línea del detalle de la mercancia o servicio prestado.
         * 
         */
        @XmlElement(name = "LineaDetalle", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        protected List<FacturaElectronicaCompra.DetalleServicio.LineaDetalle> lineaDetalle;

        /**
         * Cada línea del detalle de la mercancia o servicio prestado.
         * 
         * Gets the value of the lineaDetalle property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lineaDetalle property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getLineaDetalle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FacturaElectronicaCompra.DetalleServicio.LineaDetalle }
         * </p>
         * 
         * 
         * @return
         *     The value of the lineaDetalle property.
         */
        public List<FacturaElectronicaCompra.DetalleServicio.LineaDetalle> getLineaDetalle() {
            if (lineaDetalle == null) {
                lineaDetalle = new ArrayList<>();
            }
            return this.lineaDetalle;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="NumeroLinea" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         <element name="Codigo" minOccurs="0">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               <maxLength value="13"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="CodigoComercial" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}CodigoType" maxOccurs="5" minOccurs="0"/>
         *         <element name="Cantidad">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               <totalDigits value="16"/>
         *               <fractionDigits value="3"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="UnidadMedida" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}UnidadMedidaType"/>
         *         <element name="UnidadMedidaComercial" minOccurs="0">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               <maxLength value="20"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="Detalle">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               <maxLength value="200"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="PrecioUnitario" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
         *         <element name="MontoTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
         *         <element name="Descuento" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DescuentoType" maxOccurs="5" minOccurs="0"/>
         *         <element name="SubTotal" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
         *         <element name="BaseImponible" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
         *         <element name="Impuesto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}ImpuestoType" maxOccurs="unbounded" minOccurs="0"/>
         *         <element name="ImpuestoNeto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
         *         <element name="MontoTotalLinea" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numeroLinea",
            "codigo",
            "codigoComercial",
            "cantidad",
            "unidadMedida",
            "unidadMedidaComercial",
            "detalle",
            "precioUnitario",
            "montoTotal",
            "descuento",
            "subTotal",
            "baseImponible",
            "impuesto",
            "impuestoNeto",
            "montoTotalLinea"
        })
        public static class LineaDetalle {

            /**
             * Número de línea del detalle
             * 
             */
            @XmlElement(name = "NumeroLinea", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger numeroLinea;
            /**
             * Código de Producto/servicio
             * 
             */
            @XmlElement(name = "Codigo", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected String codigo;
            @XmlElement(name = "CodigoComercial", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected List<CodigoType> codigoComercial;
            /**
             * Cantidad
             * 
             */
            @XmlElement(name = "Cantidad", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected BigDecimal cantidad;
            /**
             * Unidad de medida
             * 
             */
            @XmlElement(name = "UnidadMedida", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected String unidadMedida;
            /**
             * Unidad de medida comercial
             * 
             */
            @XmlElement(name = "UnidadMedidaComercial", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected String unidadMedidaComercial;
            /**
             * Detalle de la mercancia transferida o servicio
             *                                                     prestado
             * 
             */
            @XmlElement(name = "Detalle", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected String detalle;
            /**
             * Precio Unitario
             * 
             */
            @XmlElement(name = "PrecioUnitario", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected BigDecimal precioUnitario;
            /**
             * Se obtiene de multiplicar el campo cantidad por el
             *                                                     campo precio unitario
             * 
             */
            @XmlElement(name = "MontoTotal", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected BigDecimal montoTotal;
            @XmlElement(name = "Descuento", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected List<DescuentoType> descuento;
            /**
             * Se obtiene de la resta del campo monto total menos
             *                                                     monto de descuento concedido
             * 
             */
            @XmlElement(name = "SubTotal", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected BigDecimal subTotal;
            /**
             * Base imponible especial
             * 
             */
            @XmlElement(name = "BaseImponible", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected BigDecimal baseImponible;
            /**
             * Cuando el producto o servicio este gravado con algún
             *                                                     impuesto se debe indicar cada uno de ellos.
             * 
             */
            @XmlElement(name = "Impuesto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected List<ImpuestoType> impuesto;
            /**
             * Impuesto Neto
             * 
             */
            @XmlElement(name = "ImpuestoNeto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
            protected BigDecimal impuestoNeto;
            /**
             * Existe dos maneras de obtener el resultado del campo:
             *                                                     - Cuando no existe exoneración, se obtiene de la sumatoria de los
             *                                                     campos “subtotal”, “monto del impuesto” .
             *                                                     - Cuando posee una exoneración, se obtiene de la sumatoria de los
             *                                                     campos “Subtotal”, “Impuesto Neto”
             * 
             */
            @XmlElement(name = "MontoTotalLinea", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
            protected BigDecimal montoTotalLinea;

            /**
             * Número de línea del detalle
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumeroLinea() {
                return numeroLinea;
            }

            /**
             * Sets the value of the numeroLinea property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             * @see #getNumeroLinea()
             */
            public void setNumeroLinea(BigInteger value) {
                this.numeroLinea = value;
            }

            /**
             * Código de Producto/servicio
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getCodigo()
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the codigoComercial property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the codigoComercial property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getCodigoComercial().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CodigoType }
             * </p>
             * 
             * 
             * @return
             *     The value of the codigoComercial property.
             */
            public List<CodigoType> getCodigoComercial() {
                if (codigoComercial == null) {
                    codigoComercial = new ArrayList<>();
                }
                return this.codigoComercial;
            }

            /**
             * Cantidad
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCantidad() {
                return cantidad;
            }

            /**
             * Sets the value of the cantidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getCantidad()
             */
            public void setCantidad(BigDecimal value) {
                this.cantidad = value;
            }

            /**
             * Unidad de medida
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnidadMedida() {
                return unidadMedida;
            }

            /**
             * Sets the value of the unidadMedida property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getUnidadMedida()
             */
            public void setUnidadMedida(String value) {
                this.unidadMedida = value;
            }

            /**
             * Unidad de medida comercial
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnidadMedidaComercial() {
                return unidadMedidaComercial;
            }

            /**
             * Sets the value of the unidadMedidaComercial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getUnidadMedidaComercial()
             */
            public void setUnidadMedidaComercial(String value) {
                this.unidadMedidaComercial = value;
            }

            /**
             * Detalle de la mercancia transferida o servicio
             *                                                     prestado
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetalle() {
                return detalle;
            }

            /**
             * Sets the value of the detalle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getDetalle()
             */
            public void setDetalle(String value) {
                this.detalle = value;
            }

            /**
             * Precio Unitario
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPrecioUnitario() {
                return precioUnitario;
            }

            /**
             * Sets the value of the precioUnitario property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getPrecioUnitario()
             */
            public void setPrecioUnitario(BigDecimal value) {
                this.precioUnitario = value;
            }

            /**
             * Se obtiene de multiplicar el campo cantidad por el
             *                                                     campo precio unitario
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoTotal() {
                return montoTotal;
            }

            /**
             * Sets the value of the montoTotal property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getMontoTotal()
             */
            public void setMontoTotal(BigDecimal value) {
                this.montoTotal = value;
            }

            /**
             * Gets the value of the descuento property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the descuento property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getDescuento().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DescuentoType }
             * </p>
             * 
             * 
             * @return
             *     The value of the descuento property.
             */
            public List<DescuentoType> getDescuento() {
                if (descuento == null) {
                    descuento = new ArrayList<>();
                }
                return this.descuento;
            }

            /**
             * Se obtiene de la resta del campo monto total menos
             *                                                     monto de descuento concedido
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSubTotal() {
                return subTotal;
            }

            /**
             * Sets the value of the subTotal property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getSubTotal()
             */
            public void setSubTotal(BigDecimal value) {
                this.subTotal = value;
            }

            /**
             * Base imponible especial
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBaseImponible() {
                return baseImponible;
            }

            /**
             * Sets the value of the baseImponible property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getBaseImponible()
             */
            public void setBaseImponible(BigDecimal value) {
                this.baseImponible = value;
            }

            /**
             * Cuando el producto o servicio este gravado con algún
             *                                                     impuesto se debe indicar cada uno de ellos.
             * 
             * Gets the value of the impuesto property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the impuesto property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getImpuesto().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ImpuestoType }
             * </p>
             * 
             * 
             * @return
             *     The value of the impuesto property.
             */
            public List<ImpuestoType> getImpuesto() {
                if (impuesto == null) {
                    impuesto = new ArrayList<>();
                }
                return this.impuesto;
            }

            /**
             * Impuesto Neto
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImpuestoNeto() {
                return impuestoNeto;
            }

            /**
             * Sets the value of the impuestoNeto property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getImpuestoNeto()
             */
            public void setImpuestoNeto(BigDecimal value) {
                this.impuestoNeto = value;
            }

            /**
             * Existe dos maneras de obtener el resultado del campo:
             *                                                     - Cuando no existe exoneración, se obtiene de la sumatoria de los
             *                                                     campos “subtotal”, “monto del impuesto” .
             *                                                     - Cuando posee una exoneración, se obtiene de la sumatoria de los
             *                                                     campos “Subtotal”, “Impuesto Neto”
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoTotalLinea() {
                return montoTotalLinea;
            }

            /**
             * Sets the value of the montoTotalLinea property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getMontoTotalLinea()
             */
            public void setMontoTotalLinea(BigDecimal value) {
                this.montoTotalLinea = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="TipoDoc">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <enumeration value="01"/>
     *               <enumeration value="02"/>
     *               <enumeration value="03"/>
     *               <enumeration value="04"/>
     *               <enumeration value="05"/>
     *               <enumeration value="06"/>
     *               <enumeration value="07"/>
     *               <enumeration value="08"/>
     *               <enumeration value="09"/>
     *               <enumeration value="10"/>
     *               <enumeration value="11"/>
     *               <enumeration value="12"/>
     *               <enumeration value="13"/>
     *               <enumeration value="14"/>
     *               <enumeration value="15"/>
     *               <enumeration value="99"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="Numero" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="50"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="FechaEmision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         <element name="Codigo" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <enumeration value="01"/>
     *               <enumeration value="02"/>
     *               <enumeration value="03"/>
     *               <enumeration value="04"/>
     *               <enumeration value="05"/>
     *               <enumeration value="99"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="Razon" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="180"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoDoc",
        "numero",
        "fechaEmision",
        "codigo",
        "razon"
    })
    public static class InformacionReferencia {

        /**
         * Tipo de documento de referencia. 01 Factura electrónica, 02 Nota
         *                                         de débito electrónica, 03 nota de crédito electrónica, 04 Tiquete electrónico,
         *                                         05 Nota de despacho, 06 Contrato, 07 Procedimiento, 08 Comprobante emitido en
         *                                         contigencia, 09 Devoluicion mercaderia, 10 Sustituye factura rechazada poir
         *                                         Ministerio de Hacienda, 11 Sustituye factura rechazada por el receptor del
         *                                         comprobante, 12 Sustituye factura de exportacion, 13 facturacion mes vencido, 99
         *                                         otros
         * 
         */
        @XmlElement(name = "TipoDoc", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        protected String tipoDoc;
        /**
         * Número de documento de referencia
         * 
         */
        @XmlElement(name = "Numero", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected String numero;
        /**
         * Fecha y hora de emisión del documento de referencia
         * 
         */
        @XmlElement(name = "FechaEmision", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaEmision;
        /**
         * Código de referencia. 01 Anula documento de referencia, 02 Corrige
         *                                         texto de documento de referencia, 03 Corrige monto, 04 Referencia a otro
         *                                         documento, 05 Sustituye comprobante provisional por contigencia, 99 Otros
         * 
         */
        @XmlElement(name = "Codigo", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected String codigo;
        /**
         * Razón de referencia
         * 
         */
        @XmlElement(name = "Razon", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected String razon;

        /**
         * Tipo de documento de referencia. 01 Factura electrónica, 02 Nota
         *                                         de débito electrónica, 03 nota de crédito electrónica, 04 Tiquete electrónico,
         *                                         05 Nota de despacho, 06 Contrato, 07 Procedimiento, 08 Comprobante emitido en
         *                                         contigencia, 09 Devoluicion mercaderia, 10 Sustituye factura rechazada poir
         *                                         Ministerio de Hacienda, 11 Sustituye factura rechazada por el receptor del
         *                                         comprobante, 12 Sustituye factura de exportacion, 13 facturacion mes vencido, 99
         *                                         otros
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoDoc() {
            return tipoDoc;
        }

        /**
         * Sets the value of the tipoDoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getTipoDoc()
         */
        public void setTipoDoc(String value) {
            this.tipoDoc = value;
        }

        /**
         * Número de documento de referencia
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumero() {
            return numero;
        }

        /**
         * Sets the value of the numero property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getNumero()
         */
        public void setNumero(String value) {
            this.numero = value;
        }

        /**
         * Fecha y hora de emisión del documento de referencia
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaEmision() {
            return fechaEmision;
        }

        /**
         * Sets the value of the fechaEmision property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getFechaEmision()
         */
        public void setFechaEmision(XMLGregorianCalendar value) {
            this.fechaEmision = value;
        }

        /**
         * Código de referencia. 01 Anula documento de referencia, 02 Corrige
         *                                         texto de documento de referencia, 03 Corrige monto, 04 Referencia a otro
         *                                         documento, 05 Sustituye comprobante provisional por contigencia, 99 Otros
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getCodigo()
         */
        public void setCodigo(String value) {
            this.codigo = value;
        }

        /**
         * Razón de referencia
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazon() {
            return razon;
        }

        /**
         * Sets the value of the razon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getRazon()
         */
        public void setRazon(String value) {
            this.razon = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="OtroTexto" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <simpleContent>
     *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *                 <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               </extension>
     *             </simpleContent>
     *           </complexType>
     *         </element>
     *         <element name="OtroContenido" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <any processContents='lax' namespace='##other'/>
     *                 </sequence>
     *                 <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otroTexto",
        "otroContenido"
    })
    public static class Otros {

        /**
         * Elemento opcional que se puede utilizar la almacenar texto.
         * 
         */
        @XmlElement(name = "OtroTexto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected List<FacturaElectronicaCompra.Otros.OtroTexto> otroTexto;
        /**
         * Elemento opcional que se puede utilizar para almacenar contenido
         *                                         estructurado.
         * 
         */
        @XmlElement(name = "OtroContenido", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected List<FacturaElectronicaCompra.Otros.OtroContenido> otroContenido;

        /**
         * Elemento opcional que se puede utilizar la almacenar texto.
         * 
         * Gets the value of the otroTexto property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otroTexto property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getOtroTexto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FacturaElectronicaCompra.Otros.OtroTexto }
         * </p>
         * 
         * 
         * @return
         *     The value of the otroTexto property.
         */
        public List<FacturaElectronicaCompra.Otros.OtroTexto> getOtroTexto() {
            if (otroTexto == null) {
                otroTexto = new ArrayList<>();
            }
            return this.otroTexto;
        }

        /**
         * Elemento opcional que se puede utilizar para almacenar contenido
         *                                         estructurado.
         * 
         * Gets the value of the otroContenido property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otroContenido property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getOtroContenido().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FacturaElectronicaCompra.Otros.OtroContenido }
         * </p>
         * 
         * 
         * @return
         *     The value of the otroContenido property.
         */
        public List<FacturaElectronicaCompra.Otros.OtroContenido> getOtroContenido() {
            if (otroContenido == null) {
                otroContenido = new ArrayList<>();
            }
            return this.otroContenido;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <any processContents='lax' namespace='##other'/>
         *       </sequence>
         *       <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "any"
        })
        public static class OtroContenido {

            @XmlAnyElement(lax = true)
            protected Object any;
            /**
             * Código opcional para facilitar la identificación del
             *                                                 elemento.
             * 
             */
            @XmlAttribute(name = "codigo")
            protected String codigo;

            /**
             * Gets the value of the any property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     {@link Element }
             *     
             */
            public Object getAny() {
                return any;
            }

            /**
             * Sets the value of the any property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     {@link Element }
             *     
             */
            public void setAny(Object value) {
                this.any = value;
            }

            /**
             * Código opcional para facilitar la identificación del
             *                                                 elemento.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getCodigo()
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <simpleContent>
         *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
         *       <attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     </extension>
         *   </simpleContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OtroTexto {

            @XmlValue
            protected String value;
            /**
             * Código opcional para facilitar la identificación
             *                                                         del elemento.
             * 
             */
            @XmlAttribute(name = "codigo")
            protected String codigo;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Código opcional para facilitar la identificación
             *                                                         del elemento.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getCodigo()
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="CodigoTipoMoneda" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}CodigoMonedaType" minOccurs="0"/>
     *         <element name="TotalServGravados" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalServExentos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalServExonerado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalMercanciasGravadas" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalMercanciasExentas" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalMercExonerada" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalGravado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalExento" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalExonerado" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalVenta" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *         <element name="TotalDescuentos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalVentaNeta" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *         <element name="TotalImpuesto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalOtrosCargos" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType" minOccurs="0"/>
     *         <element name="TotalComprobante" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra}DecimalDineroType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoTipoMoneda",
        "totalServGravados",
        "totalServExentos",
        "totalServExonerado",
        "totalMercanciasGravadas",
        "totalMercanciasExentas",
        "totalMercExonerada",
        "totalGravado",
        "totalExento",
        "totalExonerado",
        "totalVenta",
        "totalDescuentos",
        "totalVentaNeta",
        "totalImpuesto",
        "totalOtrosCargos",
        "totalComprobante"
    })
    public static class ResumenFactura {

        @XmlElement(name = "CodigoTipoMoneda", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected CodigoMonedaType codigoTipoMoneda;
        /**
         * Total de los servicios gravados con IV
         * 
         */
        @XmlElement(name = "TotalServGravados", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalServGravados;
        /**
         * Total de los servicios exentos de IV
         * 
         */
        @XmlElement(name = "TotalServExentos", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalServExentos;
        /**
         * Total servicios exonerados del IVA
         * 
         */
        @XmlElement(name = "TotalServExonerado", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalServExonerado;
        /**
         * Total mercancias gravadas con IV
         * 
         */
        @XmlElement(name = "TotalMercanciasGravadas", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalMercanciasGravadas;
        /**
         * Total mercancias exentas de IV
         * 
         */
        @XmlElement(name = "TotalMercanciasExentas", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalMercanciasExentas;
        /**
         * Total mercancías exoneradas del IVA
         * 
         */
        @XmlElement(name = "TotalMercExonerada", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalMercExonerada;
        /**
         * Total gravado. se obtiene de la suma del total servicios gravados
         *                                         con IV + total mercancias gravadas con IV
         * 
         */
        @XmlElement(name = "TotalGravado", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalGravado;
        /**
         * Total Exento, se obtiene de la suma de los campos total servicios
         *                                         exentos IV mas total mercancias exentas IV
         * 
         */
        @XmlElement(name = "TotalExento", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalExento;
        /**
         * Se obtiene de la suma de los campos “total servicios exonerados de
         *                                         IVA” mas “total de mercancías exoneradas del IVA”.
         * 
         */
        @XmlElement(name = "TotalExonerado", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalExonerado;
        /**
         * Se obtiene de la sumatoria de los campos “total gravado”, “total
         *                                         exento” y “Total Exonerado”.
         * 
         */
        @XmlElement(name = "TotalVenta", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        protected BigDecimal totalVenta;
        /**
         * Se obtiene de la suma de todos los campo de monto de descuento
         *                                         concedido
         * 
         */
        @XmlElement(name = "TotalDescuentos", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalDescuentos;
        /**
         * Se obtiene de la resta de los campos total venta menos total
         *                                         descuento
         * 
         */
        @XmlElement(name = "TotalVentaNeta", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        protected BigDecimal totalVentaNeta;
        /**
         * Se obtiene de la suma de todos campos monto del impuesto
         * 
         */
        @XmlElement(name = "TotalImpuesto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalImpuesto;
        /**
         * Total Otros Cargos
         * 
         */
        @XmlElement(name = "TotalOtrosCargos", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra")
        protected BigDecimal totalOtrosCargos;
        /**
         * Se obtiene de la suma de los campos “total venta neta”, “monto
         *                                         total del impuesto” y “total otros cargos” menos “total IVA devuelto”, en caso
         *                                         de contar con dichos campos.
         * 
         */
        @XmlElement(name = "TotalComprobante", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaCompra", required = true)
        protected BigDecimal totalComprobante;

        /**
         * Gets the value of the codigoTipoMoneda property.
         * 
         * @return
         *     possible object is
         *     {@link CodigoMonedaType }
         *     
         */
        public CodigoMonedaType getCodigoTipoMoneda() {
            return codigoTipoMoneda;
        }

        /**
         * Sets the value of the codigoTipoMoneda property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodigoMonedaType }
         *     
         */
        public void setCodigoTipoMoneda(CodigoMonedaType value) {
            this.codigoTipoMoneda = value;
        }

        /**
         * Total de los servicios gravados con IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalServGravados() {
            return totalServGravados;
        }

        /**
         * Sets the value of the totalServGravados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalServGravados()
         */
        public void setTotalServGravados(BigDecimal value) {
            this.totalServGravados = value;
        }

        /**
         * Total de los servicios exentos de IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalServExentos() {
            return totalServExentos;
        }

        /**
         * Sets the value of the totalServExentos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalServExentos()
         */
        public void setTotalServExentos(BigDecimal value) {
            this.totalServExentos = value;
        }

        /**
         * Total servicios exonerados del IVA
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalServExonerado() {
            return totalServExonerado;
        }

        /**
         * Sets the value of the totalServExonerado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalServExonerado()
         */
        public void setTotalServExonerado(BigDecimal value) {
            this.totalServExonerado = value;
        }

        /**
         * Total mercancias gravadas con IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalMercanciasGravadas() {
            return totalMercanciasGravadas;
        }

        /**
         * Sets the value of the totalMercanciasGravadas property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalMercanciasGravadas()
         */
        public void setTotalMercanciasGravadas(BigDecimal value) {
            this.totalMercanciasGravadas = value;
        }

        /**
         * Total mercancias exentas de IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalMercanciasExentas() {
            return totalMercanciasExentas;
        }

        /**
         * Sets the value of the totalMercanciasExentas property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalMercanciasExentas()
         */
        public void setTotalMercanciasExentas(BigDecimal value) {
            this.totalMercanciasExentas = value;
        }

        /**
         * Total mercancías exoneradas del IVA
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalMercExonerada() {
            return totalMercExonerada;
        }

        /**
         * Sets the value of the totalMercExonerada property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalMercExonerada()
         */
        public void setTotalMercExonerada(BigDecimal value) {
            this.totalMercExonerada = value;
        }

        /**
         * Total gravado. se obtiene de la suma del total servicios gravados
         *                                         con IV + total mercancias gravadas con IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalGravado() {
            return totalGravado;
        }

        /**
         * Sets the value of the totalGravado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalGravado()
         */
        public void setTotalGravado(BigDecimal value) {
            this.totalGravado = value;
        }

        /**
         * Total Exento, se obtiene de la suma de los campos total servicios
         *                                         exentos IV mas total mercancias exentas IV
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalExento() {
            return totalExento;
        }

        /**
         * Sets the value of the totalExento property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalExento()
         */
        public void setTotalExento(BigDecimal value) {
            this.totalExento = value;
        }

        /**
         * Se obtiene de la suma de los campos “total servicios exonerados de
         *                                         IVA” mas “total de mercancías exoneradas del IVA”.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalExonerado() {
            return totalExonerado;
        }

        /**
         * Sets the value of the totalExonerado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalExonerado()
         */
        public void setTotalExonerado(BigDecimal value) {
            this.totalExonerado = value;
        }

        /**
         * Se obtiene de la sumatoria de los campos “total gravado”, “total
         *                                         exento” y “Total Exonerado”.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalVenta() {
            return totalVenta;
        }

        /**
         * Sets the value of the totalVenta property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalVenta()
         */
        public void setTotalVenta(BigDecimal value) {
            this.totalVenta = value;
        }

        /**
         * Se obtiene de la suma de todos los campo de monto de descuento
         *                                         concedido
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalDescuentos() {
            return totalDescuentos;
        }

        /**
         * Sets the value of the totalDescuentos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalDescuentos()
         */
        public void setTotalDescuentos(BigDecimal value) {
            this.totalDescuentos = value;
        }

        /**
         * Se obtiene de la resta de los campos total venta menos total
         *                                         descuento
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalVentaNeta() {
            return totalVentaNeta;
        }

        /**
         * Sets the value of the totalVentaNeta property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalVentaNeta()
         */
        public void setTotalVentaNeta(BigDecimal value) {
            this.totalVentaNeta = value;
        }

        /**
         * Se obtiene de la suma de todos campos monto del impuesto
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalImpuesto() {
            return totalImpuesto;
        }

        /**
         * Sets the value of the totalImpuesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalImpuesto()
         */
        public void setTotalImpuesto(BigDecimal value) {
            this.totalImpuesto = value;
        }

        /**
         * Total Otros Cargos
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalOtrosCargos() {
            return totalOtrosCargos;
        }

        /**
         * Sets the value of the totalOtrosCargos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalOtrosCargos()
         */
        public void setTotalOtrosCargos(BigDecimal value) {
            this.totalOtrosCargos = value;
        }

        /**
         * Se obtiene de la suma de los campos “total venta neta”, “monto
         *                                         total del impuesto” y “total otros cargos” menos “total IVA devuelto”, en caso
         *                                         de contar con dichos campos.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalComprobante() {
            return totalComprobante;
        }

        /**
         * Sets the value of the totalComprobante property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getTotalComprobante()
         */
        public void setTotalComprobante(BigDecimal value) {
            this.totalComprobante = value;
        }

    }

}
