//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v44.mensaje.hacienda;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Clave">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <pattern value="\d{50,50}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NombreEmisor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="100"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TipoIdentificacionEmisor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="06"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroCedulaEmisor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="12"/>
 *               <pattern value="\d{9,12}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NombreReceptor" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="100"/>
 *               <minLength value="0"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TipoIdentificacionReceptor" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="06"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroCedulaReceptor" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="20"/>
 *               <pattern value="\d{9,20}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Mensaje">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               <enumeration value="1"/>
 *               <enumeration value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="EstadoMensaje">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="9"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DetalleMensaje">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MontoTotalImpuesto" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="18"/>
 *               <fractionDigits value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TotalFactura">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="18"/>
 *               <fractionDigits value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clave",
    "nombreEmisor",
    "tipoIdentificacionEmisor",
    "numeroCedulaEmisor",
    "nombreReceptor",
    "tipoIdentificacionReceptor",
    "numeroCedulaReceptor",
    "mensaje",
    "estadoMensaje",
    "detalleMensaje",
    "montoTotalImpuesto",
    "totalFactura",
    "signature"
})
@XmlRootElement(name = "MensajeHacienda", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")
public class MensajeHacienda {

    /**
     * Clave numérica del comprobante
     * 
     */
    @XmlElement(name = "Clave", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String clave;
    /**
     * Nombre o razón social del emisor
     * 
     */
    @XmlElement(name = "NombreEmisor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String nombreEmisor;
    /**
     * Tipo de identificacion: 01 Cedula Fisica, 02 Cedula Juridica, 03 DIMEX, 04 NITE, 05 Extranjero No Domiciliado, 06 No Contribuyente
     * 
     */
    @XmlElement(name = "TipoIdentificacionEmisor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String tipoIdentificacionEmisor;
    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX del emisor
     * 
     */
    @XmlElement(name = "NumeroCedulaEmisor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String numeroCedulaEmisor;
    /**
     * Nombre o razon social del receptor
     * 
     */
    @XmlElement(name = "NombreReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")
    protected String nombreReceptor;
    /**
     * Tipo de identificacion: 01 Cedula Fisica, 02 Cedula Juridica, 03 DIMEX, 04 NITE, 05 Extranjero No Domiciliado, 06 No Contribuyente
     * 
     */
    @XmlElementRef(name = "TipoIdentificacionReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoIdentificacionReceptor;
    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX del receptor
     * 
     */
    @XmlElementRef(name = "NumeroCedulaReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", type = JAXBElement.class, required = false)
    protected JAXBElement<String> numeroCedulaReceptor;
    /**
     * Codigo del mensaje de respuesta. 1 aceptado, 3 rechazado
     * 
     */
    @XmlElement(name = "Mensaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected BigInteger mensaje;
    @XmlElement(name = "EstadoMensaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String estadoMensaje;
    /**
     * Detalle del mensaje
     * 
     */
    @XmlElement(name = "DetalleMensaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected String detalleMensaje;
    /**
     * Monto total del impuesto, que es obligatorio si el comprobante tenga impuesto.
     * 
     */
    @XmlElement(name = "MontoTotalImpuesto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")
    protected BigDecimal montoTotalImpuesto;
    /**
     * Monto total de la factura
     * 
     */
    @XmlElement(name = "TotalFactura", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", required = true)
    protected BigDecimal totalFactura;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;

    /**
     * Clave numérica del comprobante
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClave() {
        return clave;
    }

    /**
     * Sets the value of the clave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getClave()
     */
    public void setClave(String value) {
        this.clave = value;
    }

    /**
     * Nombre o razón social del emisor
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreEmisor() {
        return nombreEmisor;
    }

    /**
     * Sets the value of the nombreEmisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNombreEmisor()
     */
    public void setNombreEmisor(String value) {
        this.nombreEmisor = value;
    }

    /**
     * Tipo de identificacion: 01 Cedula Fisica, 02 Cedula Juridica, 03 DIMEX, 04 NITE, 05 Extranjero No Domiciliado, 06 No Contribuyente
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoIdentificacionEmisor() {
        return tipoIdentificacionEmisor;
    }

    /**
     * Sets the value of the tipoIdentificacionEmisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipoIdentificacionEmisor()
     */
    public void setTipoIdentificacionEmisor(String value) {
        this.tipoIdentificacionEmisor = value;
    }

    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX del emisor
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCedulaEmisor() {
        return numeroCedulaEmisor;
    }

    /**
     * Sets the value of the numeroCedulaEmisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroCedulaEmisor()
     */
    public void setNumeroCedulaEmisor(String value) {
        this.numeroCedulaEmisor = value;
    }

    /**
     * Nombre o razon social del receptor
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreReceptor() {
        return nombreReceptor;
    }

    /**
     * Sets the value of the nombreReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNombreReceptor()
     */
    public void setNombreReceptor(String value) {
        this.nombreReceptor = value;
    }

    /**
     * Tipo de identificacion: 01 Cedula Fisica, 02 Cedula Juridica, 03 DIMEX, 04 NITE, 05 Extranjero No Domiciliado, 06 No Contribuyente
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoIdentificacionReceptor() {
        return tipoIdentificacionReceptor;
    }

    /**
     * Sets the value of the tipoIdentificacionReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getTipoIdentificacionReceptor()
     */
    public void setTipoIdentificacionReceptor(JAXBElement<String> value) {
        this.tipoIdentificacionReceptor = value;
    }

    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX del receptor
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNumeroCedulaReceptor() {
        return numeroCedulaReceptor;
    }

    /**
     * Sets the value of the numeroCedulaReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getNumeroCedulaReceptor()
     */
    public void setNumeroCedulaReceptor(JAXBElement<String> value) {
        this.numeroCedulaReceptor = value;
    }

    /**
     * Codigo del mensaje de respuesta. 1 aceptado, 3 rechazado
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getMensaje()
     */
    public void setMensaje(BigInteger value) {
        this.mensaje = value;
    }

    /**
     * Gets the value of the estadoMensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoMensaje() {
        return estadoMensaje;
    }

    /**
     * Sets the value of the estadoMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoMensaje(String value) {
        this.estadoMensaje = value;
    }

    /**
     * Detalle del mensaje
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalleMensaje() {
        return detalleMensaje;
    }

    /**
     * Sets the value of the detalleMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDetalleMensaje()
     */
    public void setDetalleMensaje(String value) {
        this.detalleMensaje = value;
    }

    /**
     * Monto total del impuesto, que es obligatorio si el comprobante tenga impuesto.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoTotalImpuesto() {
        return montoTotalImpuesto;
    }

    /**
     * Sets the value of the montoTotalImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoTotalImpuesto()
     */
    public void setMontoTotalImpuesto(BigDecimal value) {
        this.montoTotalImpuesto = value;
    }

    /**
     * Monto total de la factura
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFactura() {
        return totalFactura;
    }

    /**
     * Sets the value of the totalFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTotalFactura()
     */
    public void setTotalFactura(BigDecimal value) {
        this.totalFactura = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
