//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.03 at 02:09:39 PM CST 
//


package cr.go.hacienda.tribunet.v44.tiquete;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtrosCargosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtrosCargosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TipoDocumentoOC"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/tiqueteElectronico}TipoDocOtrosCargosType"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TipoDocumentoOTROS" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="5"/&gt;
 *               &lt;maxLength value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IdentificacionTercero" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/tiqueteElectronico}IdentificacionType" minOccurs="0"/&gt;
 *         &lt;element name="NombreTercero" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="100"/&gt;
 *               &lt;minLength value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Detalle"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="160"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PorcentajeOC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="9"/&gt;
 *               &lt;fractionDigits value="5"/&gt;
 *               &lt;minInclusive value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MontoCargo" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/tiqueteElectronico}DecimalDineroType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtrosCargosType", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/tiqueteElectronico", propOrder = {
    "tipoDocumentoOC",
    "tipoDocumentoOTROS",
    "identificacionTercero",
    "nombreTercero",
    "detalle",
    "porcentajeOC",
    "montoCargo"
})
public class OtrosCargosType {

    @XmlElement(name = "TipoDocumentoOC", required = true)
    protected String tipoDocumentoOC;
    @XmlElement(name = "TipoDocumentoOTROS")
    protected String tipoDocumentoOTROS;
    @XmlElement(name = "IdentificacionTercero")
    protected IdentificacionType identificacionTercero;
    @XmlElement(name = "NombreTercero")
    protected String nombreTercero;
    @XmlElement(name = "Detalle", required = true)
    protected String detalle;
    @XmlElement(name = "PorcentajeOC")
    protected BigDecimal porcentajeOC;
    @XmlElement(name = "MontoCargo", required = true)
    protected BigDecimal montoCargo;

    /**
     * Gets the value of the tipoDocumentoOC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumentoOC() {
        return tipoDocumentoOC;
    }

    /**
     * Sets the value of the tipoDocumentoOC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumentoOC(String value) {
        this.tipoDocumentoOC = value;
    }

    /**
     * Gets the value of the tipoDocumentoOTROS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumentoOTROS() {
        return tipoDocumentoOTROS;
    }

    /**
     * Sets the value of the tipoDocumentoOTROS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumentoOTROS(String value) {
        this.tipoDocumentoOTROS = value;
    }

    /**
     * Gets the value of the identificacionTercero property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificacionType }
     *     
     */
    public IdentificacionType getIdentificacionTercero() {
        return identificacionTercero;
    }

    /**
     * Sets the value of the identificacionTercero property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificacionType }
     *     
     */
    public void setIdentificacionTercero(IdentificacionType value) {
        this.identificacionTercero = value;
    }

    /**
     * Gets the value of the nombreTercero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreTercero() {
        return nombreTercero;
    }

    /**
     * Sets the value of the nombreTercero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreTercero(String value) {
        this.nombreTercero = value;
    }

    /**
     * Gets the value of the detalle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalle() {
        return detalle;
    }

    /**
     * Sets the value of the detalle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetalle(String value) {
        this.detalle = value;
    }

    /**
     * Gets the value of the porcentajeOC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcentajeOC() {
        return porcentajeOC;
    }

    /**
     * Sets the value of the porcentajeOC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcentajeOC(BigDecimal value) {
        this.porcentajeOC = value;
    }

    /**
     * Gets the value of the montoCargo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoCargo() {
        return montoCargo;
    }

    /**
     * Sets the value of the montoCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoCargo(BigDecimal value) {
        this.montoCargo = value;
    }

}
