//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v42y2016.nota.credito;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentificacionType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="IdentificacionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Tipo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Numero">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <pattern value="\d{9,12}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificacionType", namespace = "https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/notaCreditoElectronica", propOrder = {
    "tipo",
    "numero"
})
public class IdentificacionType {

    /**
     * Tipo de identificación: 01 Cédula Física, 02 Cédula Jurídica, 03 DIMEX, 04 NITE
     * 
     */
    @XmlElement(name = "Tipo", required = true)
    protected String tipo;
    /**
     * Número de identificación, el contribuyente debe estar inscrito ante la
     *                         Administración Tributaria
     * 
     */
    @XmlElement(name = "Numero", required = true)
    protected String numero;

    /**
     * Tipo de identificación: 01 Cédula Física, 02 Cédula Jurídica, 03 DIMEX, 04 NITE
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipo()
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Número de identificación, el contribuyente debe estar inscrito ante la
     *                         Administración Tributaria
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumero()
     */
    public void setNumero(String value) {
        this.numero = value;
    }

}
