//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v42y2016.nota.credito;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImpuestoResumenType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ImpuestoResumenType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Codigo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="06"/>
 *               <enumeration value="07"/>
 *               <enumeration value="99"/>
 *               <enumeration value="08"/>
 *               <enumeration value="09"/>
 *               <enumeration value="10"/>
 *               <enumeration value="11"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Tarifa">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="4"/>
 *               <fractionDigits value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Monto" type="{https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/notaCreditoElectronica}DecimalDineroType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImpuestoResumenType", namespace = "https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/notaCreditoElectronica", propOrder = {
    "codigo",
    "tarifa",
    "monto"
})
public class ImpuestoResumenType {

    /**
     * Código del impuesto: 01 Impuesto General sobre las ventas, 02 Impuesto Selectivo
     *                         de Consumo, 03 Impuesto único a los combustivos, 04 Impuesto específico de bebidas alcohólicas,
     *                         05 Impuesto específico sobre las bebidas envasadas sin contenido alcohólico y jabones de
     *                         tocador, 06 Impuesto a los productos de tabaco, 07 Servicios, 99 Otros, 08 Impuesto General a
     *                         las Ventas Diplomáticos, 09 Impuesto General sobre Ventas compras autorizadas, 10 Impuesto
     *                         General sobre las ventas instituciones públicas y otros organismos, 11 Impuesto Selectivo de
     *                         consumo compras autorizadas
     * 
     */
    @XmlElement(name = "Codigo", required = true)
    protected String codigo;
    /**
     * Tarifa del impuesto
     * 
     */
    @XmlElement(name = "Tarifa", required = true)
    protected BigDecimal tarifa;
    /**
     * Se obtiene de la multiplicación del campo subtotal por la tarifa del impuesto
     * 
     */
    @XmlElement(name = "Monto", required = true)
    protected BigDecimal monto;

    /**
     * Código del impuesto: 01 Impuesto General sobre las ventas, 02 Impuesto Selectivo
     *                         de Consumo, 03 Impuesto único a los combustivos, 04 Impuesto específico de bebidas alcohólicas,
     *                         05 Impuesto específico sobre las bebidas envasadas sin contenido alcohólico y jabones de
     *                         tocador, 06 Impuesto a los productos de tabaco, 07 Servicios, 99 Otros, 08 Impuesto General a
     *                         las Ventas Diplomáticos, 09 Impuesto General sobre Ventas compras autorizadas, 10 Impuesto
     *                         General sobre las ventas instituciones públicas y otros organismos, 11 Impuesto Selectivo de
     *                         consumo compras autorizadas
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigo()
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Tarifa del impuesto
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTarifa()
     */
    public void setTarifa(BigDecimal value) {
        this.tarifa = value;
    }

    /**
     * Se obtiene de la multiplicación del campo subtotal por la tarifa del impuesto
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonto() {
        return monto;
    }

    /**
     * Sets the value of the monto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMonto()
     */
    public void setMonto(BigDecimal value) {
        this.monto = value;
    }

}
