//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v42y2016.factura;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodigoType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CodigoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Tipo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Codigo">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="20"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodigoType", namespace = "https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/facturaElectronica", propOrder = {
    "tipo",
    "codigo"
})
public class CodigoType {

    /**
     * Tipo de código de producto o servicio: 01: Código del producto del vendedor, 02
     *                         Código del producto del comprador, 03 Código del producto asignado por la industria, 04 Código
     *                         de uso interno, 99 Otros
     * 
     */
    @XmlElement(name = "Tipo", required = true)
    protected String tipo;
    /**
     * Código del producto o servicio
     * 
     */
    @XmlElement(name = "Codigo", required = true)
    protected String codigo;

    /**
     * Tipo de código de producto o servicio: 01: Código del producto del vendedor, 02
     *                         Código del producto del comprador, 03 Código del producto asignado por la industria, 04 Código
     *                         de uso interno, 99 Otros
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipo()
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Código del producto o servicio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigo()
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

}
