//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v42y2016.tiquete;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExoneracionType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ExoneracionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TipoDocumento">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroDocumento">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="17"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NombreInstitucion">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="100"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="FechaEmision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="MontoImpuesto" type="{https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/tiqueteElectronico}DecimalDineroType"/>
 *         <element name="PorcentajeCompra">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               <totalDigits value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExoneracionType", namespace = "https://www.hacienda.go.cr/ATV/docs/esquemas/2016/v4.2/tiqueteElectronico", propOrder = {
    "tipoDocumento",
    "numeroDocumento",
    "nombreInstitucion",
    "fechaEmision",
    "montoImpuesto",
    "porcentajeCompra"
})
public class ExoneracionType {

    /**
     * Tipo de documento de exoneración o autorización. 01 Compras Autorizadas, 02 Ventas
     *                         exentas a diplomáticos, 03 Orden de compra (instituciones públicas y otros organismos), 04
     *                         Exenciones Dirección General de Hacienda, 05 Zonas Francas, 99 Otros
     * 
     */
    @XmlElement(name = "TipoDocumento", required = true)
    protected String tipoDocumento;
    /**
     * Número de documento de exoneración o autorización
     * 
     */
    @XmlElement(name = "NumeroDocumento", required = true)
    protected String numeroDocumento;
    /**
     * Nombre de la institución o dependencia que emitió la exoneración
     * 
     */
    @XmlElement(name = "NombreInstitucion", required = true)
    protected String nombreInstitucion;
    /**
     * Fecha y hora de la emisión del documento de exoneración o autorización.
     * 
     */
    @XmlElement(name = "FechaEmision", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEmision;
    /**
     * Monto del impuesto exonerado o autorizado sin impuestos
     * 
     */
    @XmlElement(name = "MontoImpuesto", required = true)
    protected BigDecimal montoImpuesto;
    /**
     * Porcentaje de la compra autorizada o exonerada
     * 
     */
    @XmlElement(name = "PorcentajeCompra", required = true)
    protected BigInteger porcentajeCompra;

    /**
     * Tipo de documento de exoneración o autorización. 01 Compras Autorizadas, 02 Ventas
     *                         exentas a diplomáticos, 03 Orden de compra (instituciones públicas y otros organismos), 04
     *                         Exenciones Dirección General de Hacienda, 05 Zonas Francas, 99 Otros
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipoDocumento()
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Número de documento de exoneración o autorización
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    /**
     * Sets the value of the numeroDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroDocumento()
     */
    public void setNumeroDocumento(String value) {
        this.numeroDocumento = value;
    }

    /**
     * Nombre de la institución o dependencia que emitió la exoneración
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreInstitucion() {
        return nombreInstitucion;
    }

    /**
     * Sets the value of the nombreInstitucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNombreInstitucion()
     */
    public void setNombreInstitucion(String value) {
        this.nombreInstitucion = value;
    }

    /**
     * Fecha y hora de la emisión del documento de exoneración o autorización.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmision() {
        return fechaEmision;
    }

    /**
     * Sets the value of the fechaEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getFechaEmision()
     */
    public void setFechaEmision(XMLGregorianCalendar value) {
        this.fechaEmision = value;
    }

    /**
     * Monto del impuesto exonerado o autorizado sin impuestos
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoImpuesto() {
        return montoImpuesto;
    }

    /**
     * Sets the value of the montoImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoImpuesto()
     */
    public void setMontoImpuesto(BigDecimal value) {
        this.montoImpuesto = value;
    }

    /**
     * Porcentaje de la compra autorizada o exonerada
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPorcentajeCompra() {
        return porcentajeCompra;
    }

    /**
     * Sets the value of the porcentajeCompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getPorcentajeCompra()
     */
    public void setPorcentajeCompra(BigInteger value) {
        this.porcentajeCompra = value;
    }

}
