//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v44.mensaje.receptor;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Clave">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <pattern value="\d{50,50}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroCedulaEmisor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="12"/>
 *               <pattern value="\d{9,12}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="FechaEmisionDoc" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="Mensaje">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               <enumeration value="1"/>
 *               <enumeration value="2"/>
 *               <enumeration value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DetalleMensaje" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="160"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MontoTotalImpuesto" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="18"/>
 *               <fractionDigits value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CodigoActividad" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="6"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CondicionImpuesto" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MontoTotalImpuestoAcreditar" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor}DecimalDineroType" minOccurs="0"/>
 *         <element name="MontoTotalDeGastoAplicable" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor}DecimalDineroType" minOccurs="0"/>
 *         <element name="TotalFactura">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="18"/>
 *               <fractionDigits value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroCedulaReceptor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="20"/>
 *               <pattern value="\d{9,12}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NumeroConsecutivoReceptor">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="20"/>
 *               <pattern value="\d{20,20}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clave",
    "numeroCedulaEmisor",
    "fechaEmisionDoc",
    "mensaje",
    "detalleMensaje",
    "montoTotalImpuesto",
    "codigoActividad",
    "condicionImpuesto",
    "montoTotalImpuestoAcreditar",
    "montoTotalDeGastoAplicable",
    "totalFactura",
    "numeroCedulaReceptor",
    "numeroConsecutivoReceptor",
    "signature"
})
@XmlRootElement(name = "MensajeReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
public class MensajeReceptor {

    /**
     * Clave numérica del comprobante
     * 
     */
    @XmlElement(name = "Clave", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected String clave;
    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX/Extranjero No Domiciliado/No Contribuyente del vendedor
     * 
     */
    @XmlElement(name = "NumeroCedulaEmisor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected String numeroCedulaEmisor;
    /**
     * Fecha de emision de la confirmación
     * 
     */
    @XmlElement(name = "FechaEmisionDoc", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEmisionDoc;
    /**
     * Codigo del mensaje de respuesta. 1 aceptado, 2 aceptado parcialmente, 3 rechazado
     * 
     */
    @XmlElement(name = "Mensaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected BigInteger mensaje;
    /**
     * Detalle del mensaje
     * 
     */
    @XmlElement(name = "DetalleMensaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected String detalleMensaje;
    /**
     * Monto total del impuesto, que es obligatorio si el comprobante tenga impuesto.
     * 
     */
    @XmlElement(name = "MontoTotalImpuesto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected BigDecimal montoTotalImpuesto;
    /**
     * Código Actividad Económica
     * 
     */
    @XmlElement(name = "CodigoActividad", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected String codigoActividad;
    /**
     * Condición del IVA. 01 General Credito IVA, 02 General Crédito parcial del IVA, 03 Bienes de Capital, 04 Gasto corriente no genera crédito, 05 Proporcionalidad
     * 
     */
    @XmlElement(name = "CondicionImpuesto", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected String condicionImpuesto;
    /**
     * Monto del Impuesto acreditar
     * 
     */
    @XmlElement(name = "MontoTotalImpuestoAcreditar", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected BigDecimal montoTotalImpuestoAcreditar;
    /**
     * Monto total del gasto a aplicar
     * 
     */
    @XmlElement(name = "MontoTotalDeGastoAplicable", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor")
    protected BigDecimal montoTotalDeGastoAplicable;
    /**
     * Monto total de la factura
     * 
     */
    @XmlElement(name = "TotalFactura", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected BigDecimal totalFactura;
    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX/Extranjero No Domiciliado/No Contribuyente del comprador
     * 
     */
    @XmlElement(name = "NumeroCedulaReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected String numeroCedulaReceptor;
    /**
     * Numeración consecutiva de los mensajes de confirmación
     * 
     */
    @XmlElement(name = "NumeroConsecutivoReceptor", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor", required = true)
    protected String numeroConsecutivoReceptor;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;

    /**
     * Clave numérica del comprobante
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClave() {
        return clave;
    }

    /**
     * Sets the value of the clave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getClave()
     */
    public void setClave(String value) {
        this.clave = value;
    }

    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX/Extranjero No Domiciliado/No Contribuyente del vendedor
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCedulaEmisor() {
        return numeroCedulaEmisor;
    }

    /**
     * Sets the value of the numeroCedulaEmisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroCedulaEmisor()
     */
    public void setNumeroCedulaEmisor(String value) {
        this.numeroCedulaEmisor = value;
    }

    /**
     * Fecha de emision de la confirmación
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmisionDoc() {
        return fechaEmisionDoc;
    }

    /**
     * Sets the value of the fechaEmisionDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getFechaEmisionDoc()
     */
    public void setFechaEmisionDoc(XMLGregorianCalendar value) {
        this.fechaEmisionDoc = value;
    }

    /**
     * Codigo del mensaje de respuesta. 1 aceptado, 2 aceptado parcialmente, 3 rechazado
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getMensaje()
     */
    public void setMensaje(BigInteger value) {
        this.mensaje = value;
    }

    /**
     * Detalle del mensaje
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalleMensaje() {
        return detalleMensaje;
    }

    /**
     * Sets the value of the detalleMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDetalleMensaje()
     */
    public void setDetalleMensaje(String value) {
        this.detalleMensaje = value;
    }

    /**
     * Monto total del impuesto, que es obligatorio si el comprobante tenga impuesto.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoTotalImpuesto() {
        return montoTotalImpuesto;
    }

    /**
     * Sets the value of the montoTotalImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoTotalImpuesto()
     */
    public void setMontoTotalImpuesto(BigDecimal value) {
        this.montoTotalImpuesto = value;
    }

    /**
     * Código Actividad Económica
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoActividad() {
        return codigoActividad;
    }

    /**
     * Sets the value of the codigoActividad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigoActividad()
     */
    public void setCodigoActividad(String value) {
        this.codigoActividad = value;
    }

    /**
     * Condición del IVA. 01 General Credito IVA, 02 General Crédito parcial del IVA, 03 Bienes de Capital, 04 Gasto corriente no genera crédito, 05 Proporcionalidad
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondicionImpuesto() {
        return condicionImpuesto;
    }

    /**
     * Sets the value of the condicionImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCondicionImpuesto()
     */
    public void setCondicionImpuesto(String value) {
        this.condicionImpuesto = value;
    }

    /**
     * Monto del Impuesto acreditar
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoTotalImpuestoAcreditar() {
        return montoTotalImpuestoAcreditar;
    }

    /**
     * Sets the value of the montoTotalImpuestoAcreditar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoTotalImpuestoAcreditar()
     */
    public void setMontoTotalImpuestoAcreditar(BigDecimal value) {
        this.montoTotalImpuestoAcreditar = value;
    }

    /**
     * Monto total del gasto a aplicar
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoTotalDeGastoAplicable() {
        return montoTotalDeGastoAplicable;
    }

    /**
     * Sets the value of the montoTotalDeGastoAplicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoTotalDeGastoAplicable()
     */
    public void setMontoTotalDeGastoAplicable(BigDecimal value) {
        this.montoTotalDeGastoAplicable = value;
    }

    /**
     * Monto total de la factura
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFactura() {
        return totalFactura;
    }

    /**
     * Sets the value of the totalFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTotalFactura()
     */
    public void setTotalFactura(BigDecimal value) {
        this.totalFactura = value;
    }

    /**
     * Número de cédula fisica/jurídica/NITE/DIMEX/Extranjero No Domiciliado/No Contribuyente del comprador
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCedulaReceptor() {
        return numeroCedulaReceptor;
    }

    /**
     * Sets the value of the numeroCedulaReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroCedulaReceptor()
     */
    public void setNumeroCedulaReceptor(String value) {
        this.numeroCedulaReceptor = value;
    }

    /**
     * Numeración consecutiva de los mensajes de confirmación
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroConsecutivoReceptor() {
        return numeroConsecutivoReceptor;
    }

    /**
     * Sets the value of the numeroConsecutivoReceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNumeroConsecutivoReceptor()
     */
    public void setNumeroConsecutivoReceptor(String value) {
        this.numeroConsecutivoReceptor = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
