//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v44.nota.debito;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImpuestoType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ImpuestoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Codigo" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}CodigoImpuestoType"/>
 *         <element name="CodigoImpuestoOTRO" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="5"/>
 *               <maxLength value="100"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CodigoTarifaIVA" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}CodigoTarifaIVAType" minOccurs="0"/>
 *         <element name="Tarifa" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="4"/>
 *               <fractionDigits value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="FactorCalculoIVA" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="5"/>
 *               <fractionDigits value="4"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DatosImpuestoEspecifico" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="CantidadUnidadMedida">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         <totalDigits value="7"/>
 *                         <fractionDigits value="2"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="Porcentaje" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         <totalDigits value="4"/>
 *                         <fractionDigits value="2"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="Proporcion" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         <totalDigits value="5"/>
 *                         <fractionDigits value="2"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="VolumenUnidadConsumo" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         <totalDigits value="7"/>
 *                         <fractionDigits value="2"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="ImpuestoUnidad" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}DecimalDineroType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Monto" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}DecimalDineroType"/>
 *         <element name="MontoExportacion" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}DecimalDineroType" minOccurs="0"/>
 *         <element name="Exoneracion" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}ExoneracionType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImpuestoType", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica", propOrder = {
    "codigo",
    "codigoImpuestoOTRO",
    "codigoTarifaIVA",
    "tarifa",
    "factorCalculoIVA",
    "datosImpuestoEspecifico",
    "monto",
    "montoExportacion",
    "exoneracion"
})
public class ImpuestoType {

    /**
     * Código del impuesto: 01 Impuesto al valor agregado, 02 Impuesto Selectivo de Consumo, 03 Impuesto único a los combustivos, 04 Impuesto específico de bebidas alcohólicas, 05 Impuesto específico sobre las bebidas envasadas sin contenido alcohólico y jabones de tocador, 06 Impuesto a los productos de tabaco, 07 IVA (cálculo especial), 08 IVA Regimen de Bienes Usados (Factor), 12 Impuesto Especifico al cemento, 99 Otros
     * 
     */
    @XmlElement(name = "Codigo", required = true)
    protected String codigo;
    /**
     * Será obligatorio en caso de utilizar el código 99 de “Otros” de la nota 8. Se debe describir puntualmente el impuesto
     * utilizado
     * 
     */
    @XmlElement(name = "CodigoImpuestoOTRO")
    protected String codigoImpuestoOTRO;
    /**
     * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este
     * campo, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de los componentes del surtido que se deben incluir en estos
     * casos. La eventual validación de la consistencia de los impuestos calculados y aplicación de tarifas se hará sobre las líneas individuales de detalle.
     * 
     */
    @XmlElement(name = "CodigoTarifaIVA")
    protected String codigoTarifaIVA;
    /**
     * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este campo, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de componentes del surtido que se deben incluir en estos casos. La eventual validación de la consistencia de los impuestos calculados y aplicación de tarifas se hará sobre las líneas individuales de detalle.
     * 
     */
    @XmlElement(name = "Tarifa")
    protected BigDecimal tarifa;
    /**
     * Este campo es de condición obligatoria, cuando el producto/servicio posea un factor para su cálculo.
     * Cuando en el código de impuesto se defina IVA Bienes Usados se deberá utilizar este campo con el factor establecido por el Ministerio de Hacienda
     * 
     */
    @XmlElement(name = "FactorCalculoIVA")
    protected BigDecimal factorCalculoIVA;
    /**
     * Tipo complejo con el detalle para calcular impuestos específicos no tarifarios. Este campo es de condición obligatoria, cuando se utilicen
     * los códigos de impuesto 03, 04, 05, 06 de la nota 8 y agrupará los campos requeridos para el cálculo de estos impuestos
     * 
     */
    @XmlElement(name = "DatosImpuestoEspecifico")
    protected ImpuestoType.DatosImpuestoEspecifico datosImpuestoEspecifico;
    /**
     * Monto del impuesto
     * 
     */
    @XmlElement(name = "Monto", required = true)
    protected BigDecimal monto;
    /**
     * Uso exclusivo para exportación de mercancías que apliquen impuestos especiales. También podrá ser utilizado en las notas de crédito y débito según corresponda. Cuando se utilicen CAByS de servicios no se verificará
     * 
     */
    @XmlElement(name = "MontoExportacion")
    protected BigDecimal montoExportacion;
    @XmlElement(name = "Exoneracion")
    protected ExoneracionType exoneracion;

    /**
     * Código del impuesto: 01 Impuesto al valor agregado, 02 Impuesto Selectivo de Consumo, 03 Impuesto único a los combustivos, 04 Impuesto específico de bebidas alcohólicas, 05 Impuesto específico sobre las bebidas envasadas sin contenido alcohólico y jabones de tocador, 06 Impuesto a los productos de tabaco, 07 IVA (cálculo especial), 08 IVA Regimen de Bienes Usados (Factor), 12 Impuesto Especifico al cemento, 99 Otros
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigo()
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Será obligatorio en caso de utilizar el código 99 de “Otros” de la nota 8. Se debe describir puntualmente el impuesto
     * utilizado
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoImpuestoOTRO() {
        return codigoImpuestoOTRO;
    }

    /**
     * Sets the value of the codigoImpuestoOTRO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigoImpuestoOTRO()
     */
    public void setCodigoImpuestoOTRO(String value) {
        this.codigoImpuestoOTRO = value;
    }

    /**
     * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este
     * campo, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de los componentes del surtido que se deben incluir en estos
     * casos. La eventual validación de la consistencia de los impuestos calculados y aplicación de tarifas se hará sobre las líneas individuales de detalle.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTarifaIVA() {
        return codigoTarifaIVA;
    }

    /**
     * Sets the value of the codigoTarifaIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodigoTarifaIVA()
     */
    public void setCodigoTarifaIVA(String value) {
        this.codigoTarifaIVA = value;
    }

    /**
     * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este campo, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de componentes del surtido que se deben incluir en estos casos. La eventual validación de la consistencia de los impuestos calculados y aplicación de tarifas se hará sobre las líneas individuales de detalle.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTarifa()
     */
    public void setTarifa(BigDecimal value) {
        this.tarifa = value;
    }

    /**
     * Este campo es de condición obligatoria, cuando el producto/servicio posea un factor para su cálculo.
     * Cuando en el código de impuesto se defina IVA Bienes Usados se deberá utilizar este campo con el factor establecido por el Ministerio de Hacienda
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFactorCalculoIVA() {
        return factorCalculoIVA;
    }

    /**
     * Sets the value of the factorCalculoIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getFactorCalculoIVA()
     */
    public void setFactorCalculoIVA(BigDecimal value) {
        this.factorCalculoIVA = value;
    }

    /**
     * Tipo complejo con el detalle para calcular impuestos específicos no tarifarios. Este campo es de condición obligatoria, cuando se utilicen
     * los códigos de impuesto 03, 04, 05, 06 de la nota 8 y agrupará los campos requeridos para el cálculo de estos impuestos
     * 
     * @return
     *     possible object is
     *     {@link ImpuestoType.DatosImpuestoEspecifico }
     *     
     */
    public ImpuestoType.DatosImpuestoEspecifico getDatosImpuestoEspecifico() {
        return datosImpuestoEspecifico;
    }

    /**
     * Sets the value of the datosImpuestoEspecifico property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpuestoType.DatosImpuestoEspecifico }
     *     
     * @see #getDatosImpuestoEspecifico()
     */
    public void setDatosImpuestoEspecifico(ImpuestoType.DatosImpuestoEspecifico value) {
        this.datosImpuestoEspecifico = value;
    }

    /**
     * Monto del impuesto
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonto() {
        return monto;
    }

    /**
     * Sets the value of the monto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMonto()
     */
    public void setMonto(BigDecimal value) {
        this.monto = value;
    }

    /**
     * Uso exclusivo para exportación de mercancías que apliquen impuestos especiales. También podrá ser utilizado en las notas de crédito y débito según corresponda. Cuando se utilicen CAByS de servicios no se verificará
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoExportacion() {
        return montoExportacion;
    }

    /**
     * Sets the value of the montoExportacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoExportacion()
     */
    public void setMontoExportacion(BigDecimal value) {
        this.montoExportacion = value;
    }

    /**
     * Gets the value of the exoneracion property.
     * 
     * @return
     *     possible object is
     *     {@link ExoneracionType }
     *     
     */
    public ExoneracionType getExoneracion() {
        return exoneracion;
    }

    /**
     * Sets the value of the exoneracion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExoneracionType }
     *     
     */
    public void setExoneracion(ExoneracionType value) {
        this.exoneracion = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="CantidadUnidadMedida">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               <totalDigits value="7"/>
     *               <fractionDigits value="2"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="Porcentaje" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               <totalDigits value="4"/>
     *               <fractionDigits value="2"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="Proporcion" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               <totalDigits value="5"/>
     *               <fractionDigits value="2"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="VolumenUnidadConsumo" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               <totalDigits value="7"/>
     *               <fractionDigits value="2"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="ImpuestoUnidad" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica}DecimalDineroType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cantidadUnidadMedida",
        "porcentaje",
        "proporcion",
        "volumenUnidadConsumo",
        "impuestoUnidad"
    })
    public static class DatosImpuestoEspecifico {

        /**
         * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este
         * campo, para los códigos de impuesto 04, 05, 06 de la nota 8, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de
         * componentes del surtido que se deben incluir en estos casos
         * 
         */
        @XmlElement(name = "CantidadUnidadMedida", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica", required = true)
        protected BigDecimal cantidadUnidadMedida;
        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 04 de la nota 8
         * 
         */
        @XmlElement(name = "Porcentaje", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica")
        protected BigDecimal porcentaje;
        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 04 de la nota 8 Este campo se obtiene de multiplicar la “Cantidad de la unidad de medida a utilizar” por el “Porcentaje”
         * 
         */
        @XmlElement(name = "Proporcion", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica")
        protected BigDecimal proporcion;
        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 05 de la nota 8
         * 
         */
        @XmlElement(name = "VolumenUnidadConsumo", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica")
        protected BigDecimal volumenUnidadConsumo;
        /**
         * Este campo es de condición obligatoria, cuando se utilicen los códigos de impuesto 03, 04, 05 y 06 de la nota 8
         * 
         */
        @XmlElement(name = "ImpuestoUnidad", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica", required = true)
        protected BigDecimal impuestoUnidad;

        /**
         * En el caso que se utilice el nodo “Detalle de productos del surtido, paquetes o combos”, no se deberá utilizar este
         * campo, para los códigos de impuesto 04, 05, 06 de la nota 8, ya que el impuesto se calcula como la suma de los montos de impuestos individuales de las líneas de detalle de
         * componentes del surtido que se deben incluir en estos casos
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCantidadUnidadMedida() {
            return cantidadUnidadMedida;
        }

        /**
         * Sets the value of the cantidadUnidadMedida property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getCantidadUnidadMedida()
         */
        public void setCantidadUnidadMedida(BigDecimal value) {
            this.cantidadUnidadMedida = value;
        }

        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 04 de la nota 8
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPorcentaje() {
            return porcentaje;
        }

        /**
         * Sets the value of the porcentaje property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getPorcentaje()
         */
        public void setPorcentaje(BigDecimal value) {
            this.porcentaje = value;
        }

        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 04 de la nota 8 Este campo se obtiene de multiplicar la “Cantidad de la unidad de medida a utilizar” por el “Porcentaje”
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getProporcion() {
            return proporcion;
        }

        /**
         * Sets the value of the proporcion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getProporcion()
         */
        public void setProporcion(BigDecimal value) {
            this.proporcion = value;
        }

        /**
         * Este campo es de condición obligatoria, cuando se utilice el código de impuesto 05 de la nota 8
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getVolumenUnidadConsumo() {
            return volumenUnidadConsumo;
        }

        /**
         * Sets the value of the volumenUnidadConsumo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getVolumenUnidadConsumo()
         */
        public void setVolumenUnidadConsumo(BigDecimal value) {
            this.volumenUnidadConsumo = value;
        }

        /**
         * Este campo es de condición obligatoria, cuando se utilicen los códigos de impuesto 03, 04, 05 y 06 de la nota 8
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getImpuestoUnidad() {
            return impuestoUnidad;
        }

        /**
         * Sets the value of the impuestoUnidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getImpuestoUnidad()
         */
        public void setImpuestoUnidad(BigDecimal value) {
            this.impuestoUnidad = value;
        }

    }

}
