//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v44.nota.credito;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmisorType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EmisorType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Nombre">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="100"/>
 *               <minLength value="5"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Identificacion" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica}IdentificacionType"/>
 *         <element name="Registrofiscal8707" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="12"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NombreComercial" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="80"/>
 *               <minLength value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Ubicacion" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica}UbicacionType" minOccurs="0"/>
 *         <element name="Telefono" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica}TelefonoType" minOccurs="0"/>
 *         <element name="CorreoElectronico" maxOccurs="4" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="160"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmisorType", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica", propOrder = {
    "nombre",
    "identificacion",
    "registrofiscal8707",
    "nombreComercial",
    "ubicacion",
    "telefono",
    "correoElectronico"
})
public class EmisorType {

    /**
     * Nombre o razon social
     * 
     */
    @XmlElement(name = "Nombre", required = true)
    protected String nombre;
    @XmlElement(name = "Identificacion", required = true)
    protected IdentificacionType identificacion;
    /**
     * Campo condicional. Se convierte en carácter obligatorio cuando se
     * estén facturando códigosCAByS de bebidas alcohólicas según la Ley
     *  8707. Contiene los datos del número de registro de bebidas
     * alcohólicas, suministrado por la Dirección General de Aduanas
     * 
     */
    @XmlElement(name = "Registrofiscal8707")
    protected String registrofiscal8707;
    /**
     * En caso de que se cuente con nombre comercial debe indicarse
     * 
     */
    @XmlElement(name = "NombreComercial")
    protected String nombreComercial;
    @XmlElement(name = "Ubicacion")
    protected UbicacionType ubicacion;
    @XmlElementRef(name = "Telefono", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica", type = JAXBElement.class, required = false)
    protected JAXBElement<TelefonoType> telefono;
    /**
     * Debe cumplir con la siguiente estructura: 
     *  \s*\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*\s*
     * 
     */
    @XmlElement(name = "CorreoElectronico")
    protected List<String> correoElectronico;

    /**
     * Nombre o razon social
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNombre()
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the identificacion property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificacionType }
     *     
     */
    public IdentificacionType getIdentificacion() {
        return identificacion;
    }

    /**
     * Sets the value of the identificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificacionType }
     *     
     */
    public void setIdentificacion(IdentificacionType value) {
        this.identificacion = value;
    }

    /**
     * Campo condicional. Se convierte en carácter obligatorio cuando se
     * estén facturando códigosCAByS de bebidas alcohólicas según la Ley
     *  8707. Contiene los datos del número de registro de bebidas
     * alcohólicas, suministrado por la Dirección General de Aduanas
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrofiscal8707() {
        return registrofiscal8707;
    }

    /**
     * Sets the value of the registrofiscal8707 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRegistrofiscal8707()
     */
    public void setRegistrofiscal8707(String value) {
        this.registrofiscal8707 = value;
    }

    /**
     * En caso de que se cuente con nombre comercial debe indicarse
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreComercial() {
        return nombreComercial;
    }

    /**
     * Sets the value of the nombreComercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNombreComercial()
     */
    public void setNombreComercial(String value) {
        this.nombreComercial = value;
    }

    /**
     * Gets the value of the ubicacion property.
     * 
     * @return
     *     possible object is
     *     {@link UbicacionType }
     *     
     */
    public UbicacionType getUbicacion() {
        return ubicacion;
    }

    /**
     * Sets the value of the ubicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link UbicacionType }
     *     
     */
    public void setUbicacion(UbicacionType value) {
        this.ubicacion = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TelefonoType }{@code >}
     *     
     */
    public JAXBElement<TelefonoType> getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TelefonoType }{@code >}
     *     
     */
    public void setTelefono(JAXBElement<TelefonoType> value) {
        this.telefono = value;
    }

    /**
     * Debe cumplir con la siguiente estructura: 
     *  \s*\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*\s*
     * 
     * Gets the value of the correoElectronico property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correoElectronico property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCorreoElectronico().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the correoElectronico property.
     */
    public List<String> getCorreoElectronico() {
        if (correoElectronico == null) {
            correoElectronico = new ArrayList<>();
        }
        return this.correoElectronico;
    }

}
