//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package cr.go.hacienda.tribunet.v43.factura.exportacion;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtrosCargosType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="OtrosCargosType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TipoDocumento">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="01"/>
 *               <enumeration value="02"/>
 *               <enumeration value="03"/>
 *               <enumeration value="04"/>
 *               <enumeration value="05"/>
 *               <enumeration value="06"/>
 *               <enumeration value="07"/>
 *               <enumeration value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Detalle">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="160"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Porcentaje" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <totalDigits value="6"/>
 *               <fractionDigits value="5"/>
 *               <minInclusive value="0"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MontoCargo" type="{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaExportacion}DecimalDineroType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtrosCargosType", namespace = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronicaExportacion", propOrder = {
    "tipoDocumento",
    "detalle",
    "porcentaje",
    "montoCargo"
})
public class OtrosCargosType {

    /**
     *  01 Contribución parafiscal, 02 Timbre de la Cruz Roja, 03 Timbre de Benemérito
     *                         Cuerpo de Bomberos de Costa Rica, 04 Cobro de un tercero, 05 Costos de Exportación, 06 Impuesto
     *                         de Servicio 10%, 07 Timbre de Colegios Profesionales, 99 Otros Cargos
     * 
     */
    @XmlElement(name = "TipoDocumento", required = true)
    protected String tipoDocumento;
    /**
     * Detalle de otros cargos
     * 
     */
    @XmlElement(name = "Detalle", required = true)
    protected String detalle;
    @XmlElement(name = "Porcentaje")
    protected BigDecimal porcentaje;
    /**
     * Monto del cargo
     * 
     */
    @XmlElement(name = "MontoCargo", required = true)
    protected BigDecimal montoCargo;

    /**
     *  01 Contribución parafiscal, 02 Timbre de la Cruz Roja, 03 Timbre de Benemérito
     *                         Cuerpo de Bomberos de Costa Rica, 04 Cobro de un tercero, 05 Costos de Exportación, 06 Impuesto
     *                         de Servicio 10%, 07 Timbre de Colegios Profesionales, 99 Otros Cargos
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTipoDocumento()
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Detalle de otros cargos
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalle() {
        return detalle;
    }

    /**
     * Sets the value of the detalle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDetalle()
     */
    public void setDetalle(String value) {
        this.detalle = value;
    }

    /**
     * Gets the value of the porcentaje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcentaje() {
        return porcentaje;
    }

    /**
     * Sets the value of the porcentaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcentaje(BigDecimal value) {
        this.porcentaje = value;
    }

    /**
     * Monto del cargo
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoCargo() {
        return montoCargo;
    }

    /**
     * Sets the value of the montoCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMontoCargo()
     */
    public void setMontoCargo(BigDecimal value) {
        this.montoCargo = value;
    }

}
